export const MOCK_PROJECTS = [
    {
        title: "Playa del Carmen",
        slug: "cortinas-antibacterianas-playa-del-carmen",
        category: "Cortinas",
        location: "Playa del Carmen, Quintana Roo",
        year: "2024",
        imageUrl: "/projects/playa-del-carmen-cortinas-antibacterianas.jpg",
        description: "Cortinas antibacterianas - Instalación de cortinas antibacterianas en instalaciones hoteleras de Playa del Carmen.",
    },
    {
        title: "Mérida",
        slug: "gases-medicinales-merida",
        category: "Gases Medicinales",
        location: "Mérida, Yucatán",
        year: "2024",
        imageUrl: "/projects/merida-gases-medicinales-y-red-de-tuberias.jpg",
        description: "Cambio de tomas de gases medicinales y red de tuberías - Actualización completa cumpliendo con normativa NFPA 99.",
    },
    {
        title: "Torre Pediátrica, Veracruz",
        slug: "paneles-terapia-torre-pediatrica-veracruz",
        category: "Gases Medicinales",
        location: "Veracruz, Veracruz",
        year: "2023",
        imageUrl: "/projects/torre-pediatrica-paneles.jpg",
        description: "Paneles para Terapia Intermedia y Terapia Intensiva, Gases Medicinales - Sistema completo de gases medicinales.",
    },
    {
        title: "Hospital Ángeles Acoxpa",
        slug: "hospital-angeles-acoxpa",
        category: "Mantenimiento",
        location: "Ciudad de México",
        year: "2023",
        imageUrl: "/projects/hospital-angeles-acoxpa.jpg",
        description: "Mantenimiento a sillas de ruedas - Servicio de mantenimiento preventivo y correctivo.",
    },
    {
        title: "Altotonga, Veracruz",
        slug: "altotonga-veracruz",
        category: "Cortinas",
        location: "Altotonga, Veracruz",
        year: "2024",
        imageUrl: "/projects/altotonga-veracruz.jpg",
        description: "Cortinas antibacterianas - Instalación de cortinas antibacterianas certificadas.",
    },
    {
        title: "Cinépolis Gran Terraza Coapa, CDMX",
        slug: "cinepolis-gran-terraza-coapa",
        category: "Correo Neumático",
        location: "Ciudad de México",
        year: "2023",
        imageUrl: "/projects/cinepolis-gran-terraza-coapa.jpg",
        description: "Suministro e Instalación de envío neumático - Sistema de transporte rápido de muestras y documentos.",
    },
    {
        title: "DIF Coacalco",
        slug: "dif-coacalco",
        category: "Infraestructura",
        location: "Coacalco, Estado de México",
        year: "2023",
        imageUrl: "/projects/dif-coacalco.jpg",
        description: "Recubrimiento de Quirófanos y sala de expulsión - Materiales de grado hospitalario.",
    },
    {
        title: "Hospital Santo Tomás Querétaro",
        slug: "hospital-santo-tomas-queretaro",
        category: "Gases Medicinales",
        location: "Querétaro, Querétaro",
        year: "2023",
        imageUrl: "/projects/hospital-santo-tomas-queretaro.jpg",
        description: "Equipamiento de Gases Medicinales - Sistema completo de gases medicinales.",
    },
    {
        title: "Hospital HMG Coyoacán",
        slug: "hospital-hmg-coyoacan",
        category: "Mantenimiento",
        location: "Ciudad de México",
        year: "2024",
        imageUrl: "/projects/hospital-hmg-coyoacan.jpg",
        description: "Mantenimiento a sillas de ruedas - Programa de mantenimiento preventivo.",
    },
    {
        title: "Sanatorio Santiago",
        slug: "sanatorio-santiago",
        category: "Mantenimiento",
        location: "Ciudad de México",
        year: "2024",
        imageUrl: "/projects/sanatorio-santiago.jpg",
        description: "Mantenimiento preventivo autoclave - Calibración y certificación de equipos.",
    },
    {
        title: "Hospital Guadalupano, Celaya, Guanajuato",
        slug: "hospital-guadalupano-celaya",
        category: "Infraestructura",
        location: "Celaya, Guanajuato",
        year: "2023",
        imageUrl: "/projects/hospital-guadalupano-celaya.jpg",
        description: "Piso conductivo - Instalación de piso conductivo en áreas críticas.",
    },
    {
        title: "Cinépolis Plaza Harbor, Mérida",
        slug: "cinepolis-plaza-harbor-merida",
        category: "Correo Neumático",
        location: "Mérida, Yucatán",
        year: "2023",
        imageUrl: "/projects/cinepolis-plaza-harbor-merida.jpg",
        description: "Suministro e Instalación de envío neumático - Sistema automatizado de transporte.",
    },
    {
        title: "Consultorios Faro del Mayab, Mérida",
        slug: "consultorios-faro-del-mayab-merida",
        category: "Cortinas",
        location: "Mérida, Yucatán",
        year: "2024",
        imageUrl: "/projects/consultorios-faro-del-mayab-merida.jpg",
        description: "Suministro e instalación de cortinas antibacterianas - Cortinas certificadas con propiedades antibacterianas.",
    },
    {
        title: "Centro de Salud, Querétaro",
        slug: "centro-salud-queretaro",
        category: "Mobiliario",
        location: "Querétaro, Querétaro",
        year: "2024",
        imageUrl: "/projects/centro-de-salud-queretaro.jpg",
        description: "Mobiliario de acero inoxidable - Fabricación e instalación de mobiliario médico.",
    },
];
